### ISSUE TITLE
getDocumentInfo should allow specifying a specific layer ID

### ISSUE THREAD

**Issue by Martin-Pitt** [adobe-photoshop/generator-core#299] opened 2015-04-20 14:51 UTC
I am trying to write a plugin which uses the Document Manager from the assets generator and I noticed that on updating text layers in Photoshop, the update event is as follows:

```
[debug:edit-image 15:38:30.605 documentmanager.js:280:22] Applying change:  {
  "version": "1.2.0",
  "timeStamp": 1429540710.601,
  "count": 208,
  "id": 360,
  "layers": [
    {
      "id": 6409,
      "text": true
    }
  ]
}
```
Please return the full object for "text".

At the moment using the Document Manager, what is happening is that all of my text layers are having their detailed text object being overwritten with the 'true' boolean.

**Comment by marekhrabe** [comment] 2015-04-20 18:06
We [discussed this a little](https://github.com/adobe-photoshop/generator-core/issues/257) some time ago, although no changes were made to address this yet. I'm +1ing for option to provide full `text` object in update events

**Comment by Martin-Pitt** [comment] 2015-04-21 19:51
Hi @timothynoel,  would this be cool with you?

**Comment by timothynoel** [comment] 2015-04-21 20:30
It's a performance issue, reporting the text info is relatively heavy-weight, so we don't report it by default.  You have to call back in with doc info to get it.

**Comment by Martin-Pitt** [comment] 2015-04-23 11:15
It isn't possible to get text info for specific layers though via doc info is there?

With say, realtime typographic updates being a use case for plugin authors, the impact on such plugins for incurring text info for the entire document for every single typographic update seems extreme.
(Especially as I work in a digital agency that loves typography and we tend to create medium to large photoshop files containing up to 30 layer comps; exacerbating the impact exponentially)

Could there be an API to enable such things to be reported from the defaults? On the other hand this would allow me to optimise the reporting even further, allowing PS to simply ignore most updates and only whitelist what I actually need.

I'm still new to Generator so I hope I'm not being unreasonable.

**Comment by timothynoel** [comment] 2015-04-23 13:06
You can get specific info on specific layers, with doc info.  The wiki API doc page has a mention of it, it involves constructing a "whichInfo" entry.  The sdk cocoa echo client app shows how to just do selected layers, but you can also specify an id, index, or index range.

**Comment by joelrbrandt** [comment] 2015-04-27 22:20
While I understand the desire for this functionality, we won't be implementing it due to the performance issues that @timothynoel raises. As he points out, when you see a `text: true` property in a document change event, you can simply request the doc info for that specific layer. Given that everything in Generator is asynchronous, and given that Photoshop computing the change info is much more expensive than the messaging overhead, you'll probably get the info just about as quickly via this route.

You could easily write a wrapper on your side for all document changed events that does a second request in the case of `text: true`, and emits a new event.

Closing this issue. If you need help doing the above @Martin-Pitt , let us know!

**Comment by Martin-Pitt** [comment] 2015-04-28 12:40
Okay, I'm just trying to wrap my head around the architecture now.

As I understand it, the current generator-core API does not support requesting specific layers (unless I completely missed something again). That I will need to write a new .jsx file and evaluate it to interact with the KVLR API to request the document with only the specific layers via the "whichInfo" entry and passing parameters.

My approach is either to work on
1. extending generator-core itself with this capability
- and do a pull request & sign the CLA.
2. evaluate a custom .jsx file in my own plugin
- and therefore having something readily portable to existing Photoshop installations.

I'd like to share back any development really, so 1. would be best but I don't know what the design decisions are behind the generator-core API.
I saw that @marekhrabe mentioned maybe having a ```getLayerInfo``` call in the other issue.

**Comment by joelrbrandt** [comment] 2015-04-28 13:12
@Martin-Pitt Apologies, I was mis-remembering the `getDocumentInfo` API -- I knew we had the `selectedLayers` parameter, which is part of the `whichInfo` API, so I mistakenly thought all of `whichInfo` was implemented inside getDocumentInfo.

I'm completely supportive of plan A -- we'd love to have your contribution. Note, however, that if you do plan A, you'll probably _also_ have to do plan B, because it will take awhile for the work in generator-core to end up in the hands of all customers. Luckily, you can easily tell what version of generator-core you're running against, and this API addition would constitute a minor version number bump.

So, I would propose doing plan B first, and getting it working the way you like it. I'd encourage you to start by essentially duplicating and elaborating the `getDocumentInfo` function and the associated `getDocumentInfo.jsx` file in your own project. Then, we can iterate on this together, and replace the current implementation in generator-core with your implementation.

I'm supportive of having a _convenience_ function in generator-core called `getLayerInfo`. But, I'd like this function to use `getDocumentInfo` internally. Since both functions would end up calling the same native API, I only want to have one JSX file involved. If we had two separate JSX implementations for those two functions, then we'd have a lot of duplicate code.

The API change I'd suggest for `getDocumentInfo` is to do the minimal thing necessary to support your use case. So, I'd propose adding an optional `layerID` parameter, and note in the documentation that `selectedLayers` and `layerID` cannot both be used at the same time (and specify a precedence if both are present). Assuming you don't need it, I would advocate for _not_ adding the layer index range portion of the API. In my experience with API design, it's best to keep APIs as small as possible until one has a concrete use case.

Is that enough to go on? Happy to help further! Thanks for volunteering to take this on.

**Comment by joelrbrandt** [comment] 2015-04-28 13:13
Changed title, tagged with feature request. Reopening.

**Comment by Martin-Pitt** [comment] 2015-04-28 15:12
Awesome. I'll follow your guidance and implement with a duplicate getDocumentInfo.jsx first.

**Comment by marekhrabe** [comment] 2015-04-28 15:42
I always implemented any functionality directly in my plugins (we have about 6 of them) and than I transformed that into generator-core. I also left the implementation in the plugins, so the code will just act as a shim for older Photoshops. I'm thrilled about `getLayerInfo` - it can speed a lot of things up :+1:

**Comment by Martin-Pitt** [comment] 2015-04-29 09:08
Hm.  I am having trouble getting the call with ```whichInfo``` to work. Either it is getting ignored (returning normal entire document as per the original ```getDocumentInfo.jsx```) or not returning anything at all (empty string?). Are there certain quirks/catches to the way it works I need to be aware of?

I have also tried replacing ```params.layerId``` with a known layer ID by hardcoding it, but that didn't work either.
```
var idNS = stringIDToTypeID("sendDocumentInfoToNetworkClient");
var desc = new ActionDescriptor();
var whichInfoDesc = new ActionDescriptor();
var layerInfoDesc = new ActionDescriptor();

layerInfoDesc.putBoolean(stringIDToTypeID("allInfo"), true);
layerInfoDesc.putInteger(stringIDToTypeID("layerID"), params.layerId); // 897);

whichInfoDesc.putObject( stringIDToTypeID("layers"), layerInfoDesc);

desc.putObject(stringIDToTypeID("whichInfo"), whichInfoDesc);

executeAction(idNS, desc, DialogModes.NO);
```


Oh by the way.
For the API design it might be a little tricky trying to mix the two (document request vs layer request), as the flags for ```layerInfoDesc``` seem they might be separate from the document flags?

Possible design might be: (in place of using ```allInfo``` by default)
```
if(flags.getTextStyles) {
    layerInfoDesc.putBoolean(stringIDToTypeID("text"), true);
}
if(flags.getPathData) {
    layerInfoDesc.putBoolean(stringIDToTypeID("path"), true);
}
```

I have Photoshop version 15.2.2 if that matters. Will try with different PSDs but trying to get whichInfo working is a bit of a showstopper right now.

**Comment by joelrbrandt** [comment] 2015-08-13 13:02
@Martin-Pitt I realize it has been a looooong time since you wrote your last comment. Unfortunately, I believe it got missed because the issue was closed (and I'm bad at using github). Apologies.

Are you still experiencing troubles? If so, we'll do our best to help!

**Comment by Martin-Pitt** [comment] 2015-08-13 18:19
I had pretty much dropped this after being unable to get that undocumented `whichInfo` feature, no matter what I tried it didn't work. I don't know whether the latest update to CC has fixed anything.

**Comment by joelrbrandt** [comment] 2015-08-17 13:13
@Martin-Pitt This won't provide much comfort, but: 1.) I was able to reproduce your problem, and 2.) I e-mailed the gentleman that can provide a fix. The good news is that it simply appears that the documetnation of `whichInfo` is incorrect, though my simple mind can't figure out how it ought to be corrected.

I'll update this issue as we get things resolved.

**Comment by Martin-Pitt** [comment] 2015-10-20 16:39
@joelrbrandt What's the status on this? :confused:

**Comment by joelrbrandt** [comment] 2015-10-20 18:13
@Martin-Pitt I don't yet have an update. I've just re-pinged the one and only person who can fix it. Sorry that isn't more useful.

**Comment by joelrbrandt** [comment] 2015-10-20 18:27
@Martin-Pitt Minor update: I got a response from the PS engineer that he can look at this next week.

**Comment by Martin-Pitt** [comment] 2015-10-22 11:49
Ok, thanks @joelrbrandt!

I hope this will be resolved. An undocumented feature might as well be a non-existent feature.

**Comment by timothynoel** [comment] 2015-10-24 05:16
I updated the [documentation] (https://github.com/adobe-photoshop/generator-core/wiki/Photoshop-Kevlar-API-Additions-for-Generatort) with a better/longer sendDocumentInfoToNetworkClien code sample with more notes about whichInfo. Upshot is that it works now as long as you format things just so. It will work a little better in 16.1, you should be able to write for both, though as 16.1 will understand the 16.0 format. The problem was mostly it's that putObject takes 3 params (key, type, descriptor).  And whichInfo currently requires both layers and comps (but you can use layerInfo and compInfo booleans to ignore them).  There's a few other oddities noted in the docs.

**Closed by timothynoel** 2015-10-24 05:16 UTC
Labels: feature request

**Comment by joelrbrandt** [comment] 2015-10-27 03:28
@Martin-Pitt Let us know if you need anything else or have any trouble with the updated documentation.

Thanks @timothynoel !
